# Generated by Django 4.1 on 2022-11-07 04:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('creator', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('date_updated', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('element_name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='blank-profile-picture.png', upload_to='element_images')),
                ('description', models.TextField(blank=True)),
                ('creator', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('date_updated', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion', models.BinaryField(default=False)),
                ('date_start', models.DateTimeField(default=datetime.datetime.now)),
                ('date_promotion', models.DateTimeField(default=datetime.datetime.now)),
                ('date_done', models.DateTimeField(default=datetime.datetime.now)),
                ('left_elem', models.CharField(max_length=100)),
                ('right_elem', models.CharField(max_length=100)),
                ('promoted_by', models.CharField(max_length=100)),
                ('ended_by', models.CharField(max_length=100)),
                ('category', models.IntegerField()),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('date_updated', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_id', models.CharField(max_length=100)),
                ('votes_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_ip', models.CharField(max_length=100)),
                ('voter_country', models.CharField(max_length=100)),
                ('voter_useragent', models.CharField(max_length=255)),
                ('element_id', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('date_updated', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
