# Generated by Django 4.1 on 2022-11-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
