# Generated by Django 4.1 on 2022-11-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_promotion_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='promotion',
            field=models.CharField(default='true', max_length=100),
        ),
    ]
