# Generated by Django 4.1 on 2022-11-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_promotion_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='status',
            field=models.CharField(default='true', max_length=100),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='promotion',
            field=models.CharField(max_length=100),
        ),
    ]
