# Generated by Django 4.1 on 2022-11-11 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_element_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
    ]
