# Generated by Django 4.1 on 2022-11-11 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_alter_category_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='ended_by',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='right_elem',
        ),
        migrations.AlterField(
            model_name='category',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='left_elem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.element'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='promoted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vote',
            name='element_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.element'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='element_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.element'),
        ),
    ]
