# Generated by Django 4.1 on 2022-11-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_promotion_ended_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='status',
            field=models.CharField(choices=[('Not started', 'Not started'), ('Promotion', 'Promotion'), ('Ended', 'Ended')], max_length=20, null=True),
        ),
    ]
