# Generated by Django 4.1 on 2022-11-11 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_alter_promotion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='ended_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ended', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotion',
            name='right_elem',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elem_2', to='core.element'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='left_elem',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elem_1', to='core.element'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='promoted_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promoted', to=settings.AUTH_USER_MODEL),
        ),
    ]
