# Generated by Django 4.1 on 2022-11-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_promotion_ended_by_promotion_right_elem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='date_updated',
        ),
        migrations.AlterField(
            model_name='element',
            name='image',
            field=models.ImageField(upload_to='element_images'),
        ),
    ]
