# Generated by Django 4.1 on 2022-11-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_promotion_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='votes_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
