# Generated by Django 4.1 on 2022-11-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_voter_ip_voter_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='counrty_code',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
