# Generated by Django 4.1 on 2022-11-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_voter_element_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='promotion_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
